title: DPP Documentation
description: Documentation for creating a wastebin that throws incorrectly sortet garbage back at the user.
theme: just-the-docs

url: https://AnnaFHub.github.io/dpp_documentation

color_scheme: nil
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  Repository: https://github.com/AnnaFHub/dpp_documentation
